// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUWzuVabQ9mjXRnOdCuK5dMoyczGS5kHU',
    appId: '1:381711656984:web:d22a9e1da3c3e9beafbb6d',
    messagingSenderId: '381711656984',
    projectId: 'flash-chat-813ce',
    authDomain: 'flash-chat-813ce.firebaseapp.com',
    storageBucket: 'flash-chat-813ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLjXiUpJ9fcI_qfsN1v3XjbdtGIJaov3Y',
    appId: '1:381711656984:android:537d7e6b0c134077afbb6d',
    messagingSenderId: '381711656984',
    projectId: 'flash-chat-813ce',
    storageBucket: 'flash-chat-813ce.appspot.com',
  );
}
